image: node:18

pipelines:
  branches:
    testing:
      - step:
          name: Install Dependencies
          caches:
            - node
          script:
            - npm install
      - step:
          name: Run Tests
          script:
            - echo "Run tests here"
      - step:
          name: Deploy to AWS Elastic Beanstalk
          deployment: testing
          script:
            - zip -r deploy.zip . -x "*.git*"
            - pipe: atlassian/aws-elasticbeanstalk-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_REGION: "us-east-1"
                APPLICATION_NAME: "ecommerce-app"
                ENVIRONMENT_NAME: "ecommerce-app-env"
                ZIP_FILE: "deploy.zip"
